pipeline:
  build_docker_image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t docker-openjdk8-git:$${DRONE_COMMIT_SHA} .
    when:
      branch: [master]
      event: [push]

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+openjdk8_git
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/docker-openjdk8-git
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+openjdk8_git
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/docker-openjdk8-git
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
